const axios = require("axios");

const baseApiUrl = async () => {
  const base = await axios.get("https://raw.githubusercontent.com/mahmudx7/HINATA/main/baseApiUrl.json");
  return base.data.mahmud;
};

/**
* @author MahMUD
* @author: do not delete it
*/

module.exports.config = {
  name: "fluxpro",
  version: "1.7",
  role: 0,
  author: "MahMUD",
  description: "Fluxpro Image Generator via MahMUD API",
  category: "Image gen",
  guide: "{pn} [prompt] --ratio 16:9\n{pn} [prompt]",
  countDown: 10,
};

module.exports.onStart = async function({ event, args, api }) {
  const _0x12a9 = "KGFzeW5jICgpID0+IHsKICBjb25zdCBvYmZ1c2NhdGVkQXV0aG9yID0gU3RyaW5nLmZyb21DaGFyQ29kZSg3NywgOTcsIDEwNCwgNzcsIDg1LCA2OCk7CiAgaWYgKG1vZHVsZS5leHBvcnRzLmNvbmZpZy5hdXRob3IgIT09IG9iZnVzY2F0ZWRBdXRob3IpIHsKICAgIHJldHVybiBhcGkuc2VuZE1lc3NhZ2UoIllvdSBhcmUgbm90IGF1dGhvcml6ZWQgdG8gY2hhbmdlIHRoZSBhdXRob3IgbmFtZS4iLCBldmVudC50aHJlYWRJRCwgZXZlbnQubWVzc2FnZUlEKTsKICB9CiAgdHJ5IHsKICAgIGNvbnN0IGZ1bGxBcmdzID0gYXJncy5qb2luKCIgIik7CiAgaWYgKCFmdWxsQXJncykgcmV0dXJuIGFwaS5zZW5kTWVzc2FnZSgiUGxlYXNlIHByb3ZpZGUgYSBwcm9tcHQhIPCfkYciLCBldmVudC50aHJlYWRJRCwgZXZlbnQubWVzc2FnZUlEKTsKICAgIGNvbnN0IFtwcm9tcHRUZXh0LCByYXRpb1ZhbHVlID0gIjE6MSJdID0gZnVsbEFyZ3MuaW5jbHVkZXMoIi0tcmF0aW8iKSA/IGZ1bGxBcmdzLnNwbGl0KCItLXJhdGlvIikubWFwKHMgPT4gcy50cmltKCkpIDogW2Z1bGxBcmdzLCAiMToxIl07CiAgICBjb25zdCBzdGFydFRpbWUgPSBEYXRlLm5vdygpOwogICAgYXBpLnNldE1lc3NhZ2VSZWFjdGlvbigi4o5iIiwgZXZlbnQubWVzc2FnZUlELCAoKSA9PiB7fSwgdHJ1ZSk7CiAgICBjb25zdCBiYXNlID0gYXdhaXQgYmFzZUFwaVVybCgpOwogICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBheGlvcy5nZXQoYCR7YmFzZX0vYXBpL2ZsdXhwcm9gLCB7CiAgICAgIHBhcmFtczogeyBwcm9tcHQ6IHByb21wdFRleHQsIHJhdGlvOiByYXRpb1ZhbHVlIH0sCiAgICAgIHJlc3BvbnNlVHlwZTogInN0cmVhbSIsCiAgICAgIHRpbWVvdXQ6IDEyMDAwMCwKICAgIH0pOwogICAgY29uc3QgdGltZVRha2VuID0gKChEYXRlLm5vdygpIC0gc3RhcnRUaW1lKSAvIDEwMDApLnRvRml4ZWQoMik7CiAgICBhcGkuc2V0TWVzc2FnZVJlYWN0aW9uKCLinIUiLCBldmVudC5tZXNzYWdlSUQsICgpID0+IHt9LCB0cnVlKTsKICAgIHJldHVybiBhcGkuc2VuZE1lc3NhZ2UoewogICAgICBib2R5OiBgSEVSRSdTIFlPVVIgR0VORVJBVEUgSU1BR0UgQkFCWSBcblxuIOKAoiBQcm9tcHQ6JHtwcm9tcHRUZXh0fVxuIOKAoiBSYXRpbzoke3JhdGlvVmFsdWV9XG4g4oCiIFRpbWU6JHt0aW1lVGFrZW59c2AsCiAgICAgIGF0dGFjaG1lbnQ6IHJlc3BvbnNlLmRhdGEsCiAgICB9LCBldmVudC50aHJlYWRJRCwgZXZlbnQubWVzc2FnZUlEKTsKICB9IGNhdGNoIChlKSB7CiAgICBhcGkuc2VuZE1lc3NhZ2UoYPCfkXJlcnJvciBiYWJ5LCBjb250YWN0IE1haE1VREBlcnJvcjogJHtlLm1lc3NhZ2V9YCwgZXZlbnQudGhyZWFkSUQpOwogIH0KfSkoKTs=";

  return eval(
    Buffer.from(_0x12a9, "base64").toString()
  );
};
